### PR TITLE
Revert "fix: Update frontend-build and frontend-platform"

### PR DESCRIPTION
**Pull request by coryleeio**
Reverts edx/frontend-app-gradebook#145

### CODE REVIEW

**Comment by morenol** [comment]
Hi @jansenk @coryleeio, could you describe the error that you had? maybe we should apply this for the Koa release

**Comment by nedbat** [comment]
@davidjoy I think you know something about this?  Where do we stand, and how do we keep Koa in sync with the master branches so that both work?

**Comment by davidjoy** [comment]
Thanks for following up @morenol and @nedbat - I'm not actually sure what the specific error was, but I'm assuming it's related to the usage of PUBLIC_PATH for the router, as it was a runtime issue.  

My guess is that a bad (empty?) value for PUBLIC_PATH made it in, and caused the router to not match any paths, so the MFE displayed no content.

**Comment by jansenk** [comment]
@morenol @davidjoy @nedbat 
Here are some screenshots from when we were triaging.PUBLIC_PATH was undefined (or null?) and we were trying to call concat on it.

8DEA3AA1-6C5E-4D9D-A4E0-B61F9A946FAD
2A5DB45D-3F50-476C-B13F-BF36D1626880

**Comment by morenol** [comment]
@davidjoy @jansenk then a reasonable fix would be to get that configuration from getConfig of frontend-platform?

import { getConfig } from '@edx/frontend-platform';

{getConfig().PUBLIC_PATH.concat(':courseId')}

right?

**Comment by davidjoy** [comment]
The problem appears to be that PUBLIC_PATH is undefined or null, as opposed to a string. Does the version in getConfig turn it into an empty string if it’s not defined?  If so, that’d work. 

Otherwise, I’d suggest just adding some defensive checking here where we want to use it.

**Comment by morenol** [comment]
Yes, it has a default there:

https://github.com/edx/frontend-platform/blob/b909372a86f4abfed5f61578f1a9e1eea55b3826/src/config.js#L36

**Pull request merged**
