### PR TITLE
feat: add compatibility with transifex

### PR DESCRIPTION
**Pull request by regisb**
Now that the frontend-app-gradebook resource was added to Transifex, we can
start pulling strings fromt there. For now, the project contains very few
translated string.

Strings were pulled by running: make pull_translations

This is for https://github.com/openedx/build-test-release-wg/issues/107

Cherry-pick of https://github.com/edx/frontend-app-gradebook/pull/217

FYI: @edx/masters-devs-gta

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @regisb! I've created [OSPR-6246](https://openedx.atlassian.net/browse/OSPR-6246) to keep track of it in JIRA.

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Comment by edx-webhook** [comment]
@jmbowman, @kdmccormick: thought you might like to know that regisb merged this pull request.

**Comment by edx-webhook** [comment]
@regisb 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-gradebook&entry.867055334=https://github.com/edx/frontend-app-gradebook/pull/218&entry.1484655318=https://github.com/regisb&entry.752974735=2021-11-30+10:14&entry.1917517419=2021-12-06+14:43&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by natabene** [comment]
@regisb Thank you for your contribution.

**Pull request merged**
