### PR TITLE
Follow up to #149

### PR DESCRIPTION
**Pull request by morenol**
Changes needed to add again support for subdirectories as a response of https://github.com/edx/frontend-app-gradebook/pull/149

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @morenol! I've created [OSPR-5249](https://openedx.atlassian.net/browse/OSPR-5249) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by morenol** [comment]
@jansenk @davidjoy This should solve the errors due to an undefined PUBLIC_PATH env that arised in the previous PR. I had to upgrade frontend-build due to an error fixed in https://github.com/edx/frontend-build/pull/136

**Comment by natabene** [comment]
@morenol Thank you for your contribution.

**Comment by nedbat** [comment]
@jansenk @davidjoy is one of you looking at this fix? We need it for Koa. Thanks.

**Review by davidjoy — APPROVED** [review]
This makes sense to me based on my understanding that `getConfig().PUBLIC_PATH` defaults to `/` as shown on this line: https://github.com/edx/frontend-platform/blob/master/src/config.js#L36

That means it'll avoid the issue where we tried to call `concat` on a `null` value, like it did in the previous version.

I can approve from that perspective, but want to let the owning team merge this so they're aware it's in; I didn't communicate well last time and we got bitten as a result.  

@jansenk or @muselesscreator - are either of you able to merge this at your convenience and give it a sanity check after?  Open edX will thank you!  (And so will I!)

**Comment by jansenk** [comment]
Yep! I'll merge and monitor

**Comment by edx-webhook** [comment]
@morenol 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-gradebook&entry.867055334=https://github.com/edx/frontend-app-gradebook/pull/152&entry.1484655318=https://github.com/morenol&entry.752974735=2020-11-24+15:39&entry.1917517419=2020-12-01+20:58&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by nedbat** [comment]
@morenol Can you make a pull request against open-release/koa.master with these changes?  I'm not sure the best practice for cherry-picking package.lock files.

**Comment by morenol** [comment]
> @morenol Can you make a pull request against open-release/koa.master with these changes? I'm not sure the best practice for cherry-picking package.lock files.

Yes, I think that we don't need the upgrade of package-lock.json there

**Pull request merged**
