### PR TITLE
docs: correct link to bulk grade management

### PR DESCRIPTION
**Pull request by pdpinch**
a.k.a. Override Learner Subsection Scores in Bulk

**TL;DR -** correct link to bulk grade management in README

**What changed?**

- there were two links in the README that went to the same section in the docs. I corrected the 2nd link. 

**Developer Checklist**

n/a for a doc change

**Testing Instructions**

click the link in README.rst

**Reviewer Checklist**

Collectively, these should be completed by reviewers of this PR:

- [ ] I've done a visual code review
- [ ] I've tested the new functionality

FYI: @edx/masters-devs-gta

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @pdpinch! I've created [OSPR-5765](https://openedx.atlassian.net/browse/OSPR-5765) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@pdpinch Thank you for your contribution, is this ready for us?

**Comment by pdpinch** [comment]
@natabene I think it's ready for review -- it's just the link change.

**Review by jansenk — APPROVED** [review]

**Comment by jansenk** [comment]
Thanks for the catch!

**Comment by edx-webhook** [comment]
@pdpinch 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-gradebook&entry.867055334=https://github.com/edx/frontend-app-gradebook/pull/177&entry.1484655318=https://github.com/pdpinch&entry.752974735=2021-05-01+15:26&entry.1917517419=2021-05-07+20:01&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
