### PR TITLE
fix: use SITE_NAME env var for index.html title

### PR DESCRIPTION
**Pull request by davidjoy**
We currently have a hard-coded “edX” string in Gradebook’s index.html file.  This replaces that string with the value of the SITE_NAME environment variable, which is set at build time from .env.development for dev, and from the build process at production build-time.  

JIRA: https://openedx.atlassian.net/browse/CENG-6

**What changed?**

This updates index.html to use SITE_NAME, and sets the .env.development default to 'localhost', and the .env default to an empty string.

**Developer Checklist**
- [x] Test suites passing
- [x] Documentation and test plan updated, if applicable
- [x] Received code-owner approving review
- [ ] Bumped version number [package.json](../package.json)

**Testing Instructions**

If you start your local development server for gradebook and load it in the browser, the title bar should default to "Gradebook | localhost" in the source of the HTML file.

**Reviewer Checklist**

Collectively, these should be completed by reviewers of this PR:

- [x] I've done a visual code review
- [x] I've tested the new functionality

FYI: @edx/masters-devs-gta

### CODE REVIEW

**Review by sarina — APPROVED** [review]
Approved, but pending how we resolve Kyle's comment in the template repo

Also remember to PR into Lilac when this merges

**Comment by nedbat** [comment]
BTW, no need to make a PR to get things into Lilac.  You can cherry-pick the commits and push if you prefer.

**Review by stvstnfrd — APPROVED** [review]

**Review by nsprenkle — APPROVED** [review]
Beautiful :shipit:

**Comment by nedbat** [comment]
@davidjoy There are a number of these changes, are you keeping track of them to make sure they all get to Lilac?

**Comment by davidjoy** [comment]
Yeah - my task was to get them into Lilac... they've all either been cherry picked or PR'd to lilac. 👍

**Pull request merged**
