### PR TITLE
Bring change from main branch to koa release

### PR DESCRIPTION
**Pull request by morenol**
This PR adds the change from https://github.com/edx/frontend-app-gradebook/pull/152.

It is needed in the cases where the environment variable PUBLIC_PATH is not defined.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @morenol! I've created [OSPR-5271](https://openedx.atlassian.net/browse/OSPR-5271) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by morenol** [comment]
@nedbat, @regisb This is the change that we applied to the main branch (I did not include the upgrade of the packages)

**Comment by natabene** [comment]
@morenol Thank you for your contribution. @nedbat Do you want me to reach out to repo owners for merging?

**Comment by nedbat** [comment]
@morenol thanks.  I'm not skilled at front-end technologies. Help me understand why the master PR includes package pinning differences, and also a different change to the `<Route` line.
/cc @davidjoy

**Comment by morenol** [comment]
@nedbat unless I am missing something, the final state of the src/index.jsx file is the same that the final state that we had after https://github.com/edx/frontend-app-gradebook/pull/152/files

The change in requirements is because in that PR, I had to upgrade frontend-build and frontend-platform to include the changes to support usage of subdirectories (The previous PR was reverted) and I used for that PR the last version of these packages because the previous version had problems with the upgrade of [eslint-plugin-import](https://github.com/edx/frontend-build/pull/136). In Koa, it is not failing because it is using a previous version of eslint-plugin-import that does not have that problem.

Maybe we could just bring to Koa all the commits from the main branch. This could be useful: https://github.com/edx/frontend-app-gradebook/pull/143/files

**Comment by nedbat** [comment]
> unless I am missing something, the final state of the src/index.jsx file is the same that the final state that we had after https://github.com/edx/frontend-app-gradebook/pull/152/files

No, you are right. I was looking at the wrong line.

> In Koa, it is not failing because it is using a previous version of eslint-plugin-import that does not have that problem.

I would prefer to keep the changes pulled into Koa as small as possible. So if Koa doesn't need fixes, we should leave it alone.  So this is good to merge as-is, correct?

**Comment by morenol** [comment]
> So this is good to merge as-is, correct?

Yes!

**Review by davidjoy — APPROVED** [review]

**Comment by edx-webhook** [comment]
@morenol 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-gradebook&entry.867055334=https://github.com/edx/frontend-app-gradebook/pull/153&entry.1484655318=https://github.com/morenol&entry.752974735=2020-12-02+04:38&entry.1917517419=2020-12-03+18:55&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
